<Project>

  <PropertyGroup>
    <DefaultNetTargetFramework>net8.0</DefaultNetTargetFramework>
    <DefaultTargetFramework>netstandard2.1</DefaultTargetFramework>
    <DefaultTestTargetFramework>net8.0</DefaultTestTargetFramework>
    <DefaultGeneratorFramework>netstandard2.0</DefaultGeneratorFramework>
    <Deterministic>true</Deterministic>
    <LangVersion>default</LangVersion>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup Label="NuGet">
    <None Include="../../icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Label="Docker">
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/obj/**/*</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/bin/**/*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' == 'true'">
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)/obj/container/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)/bin/container/</BaseOutputPath>
  </PropertyGroup>

  <Import Project="Unity3D.props" />
  <PropertyGroup Label="Unity3D">
    <UnityVersion>6000.3.4f1</UnityVersion>
    <VendoredUnityPath>$(MSBuildThisFileDirectory)unity/Unity-$(UnityVersion)</VendoredUnityPath>
    <UnityEditorDefault Condition="Exists('$(VendoredUnityPath)/UnityEditor.dll')">$(VendoredUnityPath)/UnityEditor.dll</UnityEditorDefault>
    <UnityEngineDefault Condition="Exists('$(VendoredUnityPath)/UnityEngine.dll')">$(VendoredUnityPath)/UnityEngine.dll</UnityEngineDefault>
    <UnityEditorDefault Condition="'$(UnityEditorDefault)' == ''">$(UnityHubPath)/$(UnityVersion)/$(UnityEditorPath)</UnityEditorDefault>
    <UnityEngineDefault Condition="'$(UnityEngineDefault)' == ''">$(UnityHubPath)/$(UnityVersion)/$(UnityEnginePath)</UnityEngineDefault>
    <UnityEditor Condition="'$(UnityEditor)' == ''">$(UnityEditorDefault)</UnityEditor>
    <UnityEngine Condition="'$(UnityEngine)' == ''">$(UnityEngineDefault)</UnityEngine>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' == 'true'">
    <UnityEditor>$(MSBuildStartupDirectory)/build/Managed/UnityEditor.dll</UnityEditor>
    <UnityEngine>$(MSBuildStartupDirectory)/build/Managed/UnityEngine.dll</UnityEngine>
  </PropertyGroup>

  <PropertyGroup Label="Unity3D Resolved Paths">
    <UnityEditorResolved>$([MSBuild]::NormalizePath('$(MSBuildStartupDirectory)', '$(UnityEditor)'))</UnityEditorResolved>
    <UnityEngineResolved>$([MSBuild]::NormalizePath('$(MSBuildStartupDirectory)', '$(UnityEngine)'))</UnityEngineResolved>
  </PropertyGroup>

</Project>
