<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DesperateDevs.Caching" Version="1.*" />
    <PackageReference Include="DesperateDevs.Reflection" Version="1.*" />
  </ItemGroup>
</Project>
